# docker-composeのバージョン指定
version: '3.8'

services:
  # 各コンテナをサービスと呼ぶ
  db:
    # ベースイメージを定義
    image: postgres:13.1-alpine
    environment:
      # OSのタイムゾーン
      TZ: UTC
      # postgresのタイムゾーン
      PGTZ: UTC
      # データベースのパスワード
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    # ホスト側のディレクトリをコンテナで使用する
    # volumes: ホストパス(絶対 or 相対):コンテナパス(絶対)
    ## volumsとは？→ホスト側の変更がリアルタイムで反映される
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    # ベースイメージとなるDockerfileを指定
    build:
      context: ./api
      # Dockerfileに変数を渡す
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
      command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/$WORKDIR
    # サービスの依存関係を定義(起動の順番)
    depends_on:
      - db
    # 公開用ポートを指定
    # 公開したいポート番号：コンテナポート
    ports:
      - "$API_PORT:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        API_URL: "http://localhost:$API_PORT"
    # コンテナで実行したいコマンド(CMD)
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - api